CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = 151655
DEFAULT_IM_START_INDEX=151652
DEFAULT_IM_END_INDEX=151653
DEFAULT_IMAGE_TOKEN = "<|image_pad|>"
DEFAULT_IMAGE_PATCH_TOKEN = "<|image_pad|>"
DEFAULT_IM_START_TOKEN = "<|vision_start|>"
DEFAULT_IM_END_TOKEN = "<|vision_end|>"
IMAGE_PLACEHOLDER = "<image-placeholder>"
DEFAULT_AUDIO_TOKEN = "<||audio||>"
DEFAULT_AUDIO_FEATURE_TOKEN = "<||audio_feature||>"
DEFAULT_AUDIO_START_TOKEN = "<||audio_start||>"
DEFAULT_AUDIO_END_TOKEN = "<||audio_end||>"
# AUDIO_TOKEN_INDEX = 50295
